CREATE TABLE measurement
(
    id SERIAL8 NOT NULL PRIMARY KEY,
    active BOOLEAN NOT NULL,
    created_on TIMESTAMP WITHOUT TIMEZONE NOT NULL,
    updated_on TIMESTAMP WITHOUT TIMEZONE NOT NULL,
    uid VARCHAR(255) NOT NULL,
    data BYTEA NOT NULL
)